pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                cd ai-projects/openai_self-healing-agent/ai-devops-maven
                mvn clean install > build.log || true
                '''
            }
        }

        stage('AI Debug') {
    steps {
        withCredentials([string(credentialsId: 'OPENAI_API_KEY', variable: 'OPENAI_API_KEY')]) {
            sh '''
            cd ai-projects/openai_self-healing-agent

            echo "📦 Installing Python dependencies..."
            python3 -m pip install --user -r requirements.txt

            export OPENAI_API_KEY=$OPENAI_API_KEY

            echo "🤖 Running AI Agent..."
            python3 ai-agent.py
            '''
        }
    }
}

        stage('Rebuild') {
            steps {
                sh '''
                cd ai-projects/openai_self-healing-agent/ai-devops-maven
                mvn clean install
                '''
            }
        }
    }
}
