pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main',
                    credentialsId: '77574aa6-ebb8-4641-9540-da90dbcb1576',
                    url: 'https://github.com/Rohitcs09/AI-DevOps.git'
            }
        }

        stage('Skip AI Loop') {
            steps {
                script {
                    def msg = sh(script: "git log -1 --pretty=%B", returnStdout: true).trim()
                    echo "Last commit message: ${msg}"

                    if (msg.contains("[ai]")) {
                        echo "AI commit detected → stopping loop safely"
                        currentBuild.result = 'SUCCESS'
                        return   // ✅ no failure now
                    }
                }
            }
        }

        stage('Build with Maven') {
            steps {
                sh '''
                set +e
                set -o pipefail

                cd ai-devops-project/ai-devops-maven || exit 1

                rm -f build_failed

                mvn clean install
                STATUS=$?

                if [ $STATUS -ne 0 ]; then
                    touch build_failed
                fi

                exit 0
                '''
            }
        }

        stage('Rebuild After AI Fix') {
            when {
                expression {
                    return fileExists('ai-devops-project/ai-devops-maven/build_failed')
                }
            }
            steps {
                sh '''
                cd ai-devops-project/ai-devops-maven
                mvn clean install
                '''
            }
        }
    }

    post {
        failure {
            script {
                def isFailed = fileExists('ai-devops-project/ai-devops-maven/build_failed')

                if (isFailed) {
                    echo 'Running AI Fix...'

                    withCredentials([usernamePassword(
                        credentialsId: '77574aa6-ebb8-4641-9540-da90dbcb1576',
                        usernameVariable: 'GIT_USER',
                        passwordVariable: 'GIT_PASS'
                    )]) {

                        sh '''
                        cd ai-devops-project/ai-devops-maven

                        python3 ../ai_dependency_agent.py

                        git config user.email "jenkins@ai.com"
                        git config user.name "Jenkins AI Bot"

                        git add .
                        git commit -m "[ai] auto-fix dependency issue" || echo "No changes"

                        git remote set-url origin https://$GIT_USER:$GIT_PASS@github.com/Rohitcs09/AI-DevOps.git
                        git push origin main
                        '''
                    }
                }
            }
        }
    }
}
